In [ ]:
import pickle
import numpy as np
X=np.loadtxt('wiki_prince/embedding.txt')

In [ ]:
itw=pickle.load(open('wiki_prince/itw.p','rb'))
wti=pickle.load(open('wiki_prince/wti.p','rb'))

In [10]:
man_list=[]
com_list=[]
for k,v in itw.items():
    if v[-2:]=='_1':
        man_list.append(k)
    else:
        com_list.append(k)

In [11]:
X=X[np.array(com_list),:]

new_itw={}
new_wti={}
n=0
for index in com_list:
    new_itw[n]=itw[index]
    new_wti[itw[index]]=n
    n+=1

In [12]:
itw=new_itw
wti=new_wti

In [13]:
len(X)

339863

In [101]:
for i in range(X.shape[0]):
    X[i,:]=X[i,:]/np.linalg.norm(X[i,:])

In [101]:
b_i=np.loadtxt('bias_i.txt')

In [115]:
b_i[filter_index]

array([ 0.85448372,  0.41868544,  0.1181992 , ...,  0.22399859,
        0.10890466,  0.04845205])

In [14]:
from sklearn.cluster import KMeans
import numpy as np

kmeans = KMeans(n_clusters=9, random_state=0,max_iter=500).fit(X)
kmeans.labels_

#kmeans.predict([[0, 0], [4, 4]])
#kmeans.cluster_centers_

KeyboardInterrupt: 

In [144]:
kmeans.cluster_centers_

array([[ 0.06231219,  0.05372317,  0.06133929,  0.05517024,  0.05322468,
         0.06160167,  0.05477159,  0.05404638,  0.05617272,  0.04697192,
         0.05667539,  0.05401183,  0.06198018,  0.04815207,  0.05608699,
         0.05451519,  0.05544246,  0.04752389,  0.05164554,  0.05385934,
         0.06078117,  0.05584777,  0.05179617,  0.05488365,  0.05952449,
         0.0610466 ,  0.04666387,  0.04821344,  0.05924081,  0.05404968,
         0.05855711,  0.0470559 ,  0.05030961,  0.06130334,  0.05398687,
         0.05283429,  0.0603492 ,  0.06136143,  0.04882614,  0.05480584,
         0.06200351,  0.0513078 ,  0.06181705,  0.06261825,  0.05284283,
         0.05703891,  0.0504513 ,  0.05030846,  0.04964717,  0.05527912,
         0.05505015,  0.05300997,  0.05666175,  0.05194461,  0.05285602,
         0.04745543,  0.04845737,  0.06112591,  0.0618802 ,  0.05203189,
         0.04772902,  0.04888131,  0.05516703,  0.05350052,  0.05750258,
         0.05566132,  0.05114189,  0.05625689,  0.0

In [78]:
all_words=[v for k,v in itw.items()]

In [52]:
from sklearn.neighbors import NearestNeighbors
import time
t1=time.time()
nbrs = NearestNeighbors(n_neighbors=5, algorithm='kd_tree').fit(X)
time.time()-t1

28.885169506072998

In [58]:
name='new york university_2'
distances, indices = nbrs.kneighbors(X[wti[name]].reshape(1, -1))
indices          
for i in indices[0]:
    print(i, itw[i])

2156 new york university_2
3977 nyu_2
2516 city college_2
225 columbia university_2
1533 columbia college_2


In [75]:
import pickle
d = pickle.load(file = open('yahoo.p','rb'))

In [83]:
sorted(d['shinzo abe_1'].items(), key=lambda p: p[1],reverse=True)

[('shinzo abe_1', 463),
 ('donald trump_1', 199),
 ('white house_2', 142),
 ('barack obama_1', 96),
 ('trump_1', 89),
 ('trump_2', 73),
 ('mar-a-lago_2', 71),
 ('united_2', 59),
 ('xi jinping_1', 57),
 ('sean spicer_1', 54),
 ('associated press_2', 53),
 ("donald trump's_1", 51),
 ('obama_1', 49),
 ('mike pence_1', 48),
 ('yahoo_2', 46),
 ('united nations_2', 45),
 ('vladimir putin_1', 45),
 ('melania trump_1', 39),
 ('u.n_2', 39),
 ('kim jong un_1', 37),
 ('facebook_2', 36),
 ('state_2', 31),
 ('cnn_2', 31),
 ('reuters_2', 29),
 ('kellyanne conway_1', 28),
 ('hillary clinton_1', 28),
 ('u.n. security council_2', 27),
 ('senate_2', 27),
 ('michael flynn_1', 26),
 ('nato_2', 26),
 ('donald_1', 26),
 ('mari yamaguchi_1', 25),
 ('defense_2', 25),
 ('washington post_2', 25),
 ('rex tillerson_1', 24),
 ('abc_2', 24),
 ('chinese foreign ministry_2', 23),
 ('security council_2', 23),
 ('akihito_1', 22),
 ('yoshihide suga_1', 21),
 ('ben blanchard_1', 21),
 ('un_2', 21),
 ('abc news_2', 21),
 

In [127]:
#sorted(d['apple_2'].items(), key=lambda p: p[1],reverse=True)

In [26]:
pair_list_1=['uiuc_2','nyu_2','steve jobs_1','bill gates_1','ge_2','amazon_2','google_2','boeing_2',
             'navy_2','coca cola_2','mit_2',
             'sony_2','intel_2','medtronic_2','bose_2','wells fargo_2','verizon_2','csv_2','prudential_2','ups_2']

In [27]:
pair_list_2=['university of illinois_2','new york university_2','apple_2','microsoft_2',
             'general electric_2','ebay_2',
            'ibm_2','lockheed_2','army_2','pepsi_2','stanford_2','cisco_2','ibm_2','abbott_2','jbl_2','jp morgan chase_2',
            'sprint_2','walgreen_2','state farm_2','fedex_2']

In [23]:
pair_list_1=['uiuc_1','nyu_2','steve jobs_1','bill gates_1','ge_2','amazon_2','google_2','boeing_2',
             'navy_2','coca cola_2','mit_2',
             'sony_2','intel_2','medtronic_2','wells fargo_2','verizon_2','ups_2']

In [21]:
pair_list_2=['university of illinois_2','new york university_2','microsoft_2',
             'general electric_2','ebay_2',
            'ibm_2','lockheed_2','army_2','pepsi_2','stanford_2','cisco_2','ibm_2','abbott_2','jbl_2','jp morgan chase_2',
            'sprint_2','walgreen_2','state farm_2','fedex_2']

In [27]:
pair_list_1=['uiuc_2','nyu_2','ge_2','amazon_2','google_2','boeing_2',
             'navy_2','coca cola_2','mit_2',
             'sony_2','intel_2','medtronic_2','wells fargo_2','verizon_2','csv_2','prudential_2','ups_2']

In [29]:
pair_list_2=['university of illinois_2','new york university_2',
             'general electric_2','ebay_2',
            'ibm_2','lockheed_2','army_2','pepsi_2','stanford_2','cisco_2','ibm_2','abbott_2','jp morgan chase_2',
            'sprint_2','walgreen_2','state farm_2','fedex_2']

In [79]:
z_score=[]
for i in range(len(pair_list_1)):
    name_1=pair_list_1[i]
    name_2=pair_list_2[i]

    psim=cosine_similarity(X[wti[name_1],:].reshape(1, -1),X[wti[name_2],:].reshape(1, -1))[0][0]

    sim=[]
    for i in range(3000):
        ri=np.random.randint(len(all_words))
        sim.append(cosine_similarity(X[wti[name_1],:].reshape(1, -1),X[ri,:].reshape(1, -1)))

    z_score.append((psim-np.mean(sim))/np.std(sim))
print(np.mean(z_score))
print(z_score)

-1.46351719441
[-16.093750297316184, -10.944614432122004, -16.422785514900337, -14.717344841783447, 2.7224133689390904, -0.81722797914142276, 0.22028766999495217, 11.028330462233855, 10.221139398301389, -6.7580128209025681, 0.74295771311838665, -0.22764096160578784, 17.10050388700299, -0.53989637181936045, -1.7096843259550174, 0.13563148587835924, -4.4802515827489433, 1.2084677507325703, -0.83611690308963948, 0.89725040702560199]


In [83]:
name_1='google_2'
name_2='uiuc_2'
from sklearn.metrics.pairwise import cosine_similarity
psim=cosine_similarity(X[wti[name_1],:].reshape(1, -1),X[wti[name_2],:].reshape(1, -1))
print('This pair: ',psim[0][0])
sim=[]
for i in range(3000):
    ri=np.random.randint(len(all_words))
    sim.append(cosine_similarity(X[wti[name_1],:].reshape(1, -1),X[ri,:].reshape(1, -1)))
print(np.mean(sim),np.std(sim))
print(abs(psim[0][0]-np.mean(sim))/np.std(sim))

This pair:  0.219975340903
0.213577391954 0.040629035555
0.157472331331


In [69]:
sim=[]
for i in range(30000):
    ri=np.random.randint(len(all_words))
    ai=np.random.randint(len(all_words))
    sim.append(cosine_similarity(X[ai,:].reshape(1, -1),X[ri,:].reshape(1, -1)))
print(np.mean(sim),np.std(sim))

0.730806373547 0.0657408669345


In [15]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(X[5,:].reshape(1, -1),X[11208,:].reshape(1, -1))

array([[ 0.10586997]])

In [82]:
np.unique(scomp['Industry'])

array(['Basic Industries', 'Consumer Services', 'Finance', 'Health Care',
       'Media', 'Miscellaneous', 'Public Utilities', 'Technology',
       'Transportation'], dtype=object)

In [85]:
import pandas as pd
res=pd.DataFrame({'name':all_words,'cluster':kmeans.labels_}) 

In [97]:
res[res['cluster']==3]

In [37]:
fpeople=pickle.load(open('train/Forbes_People_Final.pickle','rb'))
ncomp=pickle.load(open('train/Nasdaq_Company_Final.pickle','rb'))
scomp=pickle.load(open('train/Sec_Company_Final.pickle','rb'))
speople=pickle.load(open('train/Sec_People_Final.pickle','rb'))


In [92]:
from collections import Counter
cnt = Counter()
temp=[]
for w in all_words:
    temp.append(w[:-2])
    #temp.append(w)
cnt.update(temp)

In [93]:
print(speople[speople['People'].isin(cnt)].count())
speople[speople['People'].isin(cnt)].count()/speople.count()

People      98
Industry    98
dtype: int64


People      0.000402
Industry    0.000402
dtype: float64

In [94]:
print(scomp[scomp['Company'].isin(cnt)].count())
scomp[scomp['Company'].isin(cnt)].count()/scomp.count()

Company     713
Industry    713
dtype: int64


Company     0.012321
Industry    0.012321
dtype: float64

In [95]:
print(ncomp[ncomp['Company'].isin(cnt)].count())
ncomp[ncomp['Company'].isin(cnt)].count()/ncomp.count()

Company     360
Industry    360
dtype: int64


Company     0.075456
Industry    0.075456
dtype: float64

In [96]:
print(fpeople[fpeople['People'].isin(cnt)].count())
fpeople[fpeople['People'].isin(cnt)].count()/fpeople.count()

People      2
Industry    2
dtype: int64


People      0.001136
Industry    0.001136
dtype: float64

In [106]:
scomp_new=scomp[scomp['Company'].isin(cnt)]

In [164]:
np.unique(res.cluster)

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [121]:
res.name=res.name.apply(lambda n:n[:-2])

In [133]:
all_match={}
for ind in np.unique(scomp_new.Industry):
    cnt_list=[]
    
    
    for c in np.unique(res.cluster):
            matcher=Counter()
        
            matcher.update(scomp_new[scomp_new.Industry==ind]['Company'])
            sub_res=res[res.cluster==c]
            
            cnt_list.append(len(sub_res[sub_res.name.isin(matcher) ]))
    all_match[ind]=cnt_list
    print(cnt_list.index(max(cnt_list)))
    print(max(cnt_list))
    print('-'*10)

1
12
----------
4
14
----------
8
14
----------
2
8
----------
6
5
----------
7
15
----------
8
14
----------
4
23
----------
7
13
----------


In [178]:
assign=[1,3,8,2,6,7,3,4,5]

In [179]:
n=0
predict=[]
predict_ind=[]
for ind in np.unique(scomp_new.Industry):
    c=assign[n]
    predict+=list(res[res.cluster==c].name)
    predict_ind+=[ind]*len(list(res[res.cluster==c].name))
    n+=1

In [180]:
pred=pd.DataFrame({'name':predict,'ind':predict_ind})

In [181]:
pred=pred[pred['name'].isin(Counter(scomp.Company))]

In [182]:
score=0
for index, row in pred.iterrows():
    score+=(scomp[scomp.Company==row['name']]['Industry'].values[0]==row['ind'])

In [184]:
score/len(pred)

0.1590909090909091

In [134]:
all_match

{'Basic Industries': [8, 12, 4, 9, 6, 6, 12, 7, 4],
 'Consumer Services': [9, 8, 9, 13, 14, 5, 12, 9, 13],
 'Finance': [8, 11, 8, 7, 10, 10, 10, 6, 14],
 'Health Care': [4, 4, 8, 7, 8, 5, 4, 0, 2],
 'Media': [2, 0, 2, 1, 1, 2, 5, 2, 1],
 'Miscellaneous': [7, 12, 11, 13, 11, 13, 8, 15, 15],
 'Public Utilities': [3, 5, 6, 11, 3, 6, 4, 5, 14],
 'Technology': [8, 17, 18, 16, 23, 15, 11, 21, 11],
 'Transportation': [10, 11, 10, 6, 6, 11, 10, 13, 7]}